# - name: Making sure all hosts are available
#   hosts: all
#   become: yes
#   tasks:
#     - include_tasks: ../tasks/general/01_ping.yml

# # Docker installation
# - name: Install Docker on managers and workers
#   hosts: managers:workers
#   become: yes
#   tasks:
#     - include_tasks: ../tasks/docker/02_docker_install.yml

# # Building the storage server
# - name: Install NFS packages on data server
#   hosts: maangers:workers
#   become: yes
#   tasks:
#     - include_tasks: ../tasks/storage/03_nfs_requirements_install.yml

# # Install NFS-commons
# - name: Install NFS Common on, Managers & Workers
#   hosts: mangers:workers
#   become: yes
#   tasks:
#     - include_tasks: ../tasks/storage/04_nfs_common_requirents_install.yml

# # Mount the NFS share
# - name: Mounting Share on, Managers & Workers
#   hosts: mangers:workers
#   become: yes
#   tasks:
#     - include_tasks: ../tasks/storage/05_nfs_mounting_share.yml

# Initiate and Join the Swarm
- name: Initiating the Swarm
  hosts: managers
  become: yes
  tasks:
    - include_tasks: ../tasks/docker/06_docker_swarm_setup.yml


# Joining the Swarm
- name: Join swarm
  hosts: workers
  become: yes
  tasks:
    - include_tasks: ../tasks/docker/07_docker_swarm_join.yml