---
# Initialize Docker Swarm on first manager and set join tokens

- name: Initialize swarm on first manager
  command: "docker swarm init --advertise-addr {{ ansible_host }}"
  register: swarm_init
  run_once: true
  failed_when: swarm_init.rc not in [0,1]

- name: Retrieve manager join token
  command: "docker swarm join-token manager -q"
  register: manager_token
  run_once: true

- name: Retrieve worker join token
  command: "docker swarm join-token worker -q"
  register: worker_token
  run_once: true

- name: Set manager join command as a fact
  set_fact:
    manager_join_command: "docker swarm join --token {{ manager_token.stdout }} {{ ansible_host }}:2377"
    delete_to: workers
    delegate_fact: true


- name: Set worker join command as a fact
  set_fact:
    worker_join_command: "docker swarm join --token {{ worker_token.stdout }} {{ ansible_host }}:2377"
    delete_to: workers
    delegate_fact: true
